name: Test weather_bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8 pep8-naming flake8-broken-line flake8-return
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with flake8
      run: |
        python -m flake8

  send_message:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} - success!